# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: build_test_linux
  displayName: Build and test on Linux
  timeoutInMinutes: 30
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: |
      cmake CmakeLists.txt -DCMAKE_BUILD_TYPE=Debug -DCMAKE_BUILD_TESTS=ON $(extra_cmake_options)
      cmake --build $(Build.BinariesDirectory) -- -j$(nproc)
    displayName: Build tests
  - script: |
      ./azure-sink-test
    displayName: Run tests
