#ifndef _GST_AZURE_SINK_ERROR_H_
#define _GST_AZURE_SINK_ERROR_H_

#define NO_CONFIG 400
#define NO_CREDENTIAL 401
#define NO_DESTINATION 402

#define START_FAILED 500
#define APPEND_FAILED 501
#define FLUSH_FAILED 502
#define DESTROY_FAILED 503
#endif